_wandb:
    value:
        cli_version: 0.23.0
        e:
            e1j1r1n4nt5hipzw57m8k32va81nm90k:
                args:
                    - --sequential
                codePath: run_dense_vs_sparse.py
                codePathLocal: run_dense_vs_sparse.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "368537759744"
                        used: "125869600768"
                email: zeng-h21@mails.tsinghua.edu.cn
                executable: C:\Users\zengqiang\.conda\envs\AI\python.exe
                host: LAPTOP-QM4EL0FR
                memory:
                    total: "16969424896"
                os: Windows-10-10.0.19045-SP0
                program: D:\ZENG_Hui_files\Code\2025\AntiGravityPlay\run_dense_vs_sparse.py
                python: CPython 3.12.9
                root: D:\ZENG_Hui_files\Code\2025\AntiGravityPlay
                startedAt: "2025-11-25T12:22:51.828441Z"
                writerId: e1j1r1n4nt5hipzw57m8k32va81nm90k
        m:
            - "1": step
              "6":
                - 3
              "7": []
            - "1": epoch
              "6":
                - 3
              "7": []
            - "1": training/accuracy
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation/accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": validation/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "2": validation/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": sparsity/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": training/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
                - 24
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 512
device:
    value: cpu
dim_model:
    value: 128
learning_rate:
    value: 0.001
num_heads:
    value: 4
num_layers:
    value: 2
num_steps:
    value: 2000
operation:
    value: x+y
prime:
    value: 97
training_fraction:
    value: 0.5
weight_decay:
    value: 1
