_wandb:
    value:
        cli_version: 0.23.0
        e:
            nuuq94yvpfscz7u9czuv30g9j2n8d17f:
                args:
                    - --sequential
                codePath: run_dense_vs_sparse.py
                codePathLocal: run_dense_vs_sparse.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "368537759744"
                        used: "125902647296"
                email: zeng-h21@mails.tsinghua.edu.cn
                executable: C:\Users\zengqiang\.conda\envs\AI\python.exe
                host: LAPTOP-QM4EL0FR
                memory:
                    total: "16969424896"
                os: Windows-10-10.0.19045-SP0
                program: D:\ZENG_Hui_files\Code\2025\AntiGravityPlay\run_dense_vs_sparse.py
                python: CPython 3.12.9
                root: D:\ZENG_Hui_files\Code\2025\AntiGravityPlay
                startedAt: "2025-11-26T01:57:09.688249Z"
                writerId: nuuq94yvpfscz7u9czuv30g9j2n8d17f
        m:
            - "1": step
              "6":
                - 3
              "7": []
            - "1": epoch
              "6":
                - 3
              "7": []
            - "1": training/accuracy
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": training/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": validation/accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": validation/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.95
adam_eps:
    value: 0.1
anneal_end_ratio:
    value: 0
batch_size:
    value: 512
device:
    value: cpu
dim_model:
    value: 128
eval_every:
    value: 5
final_L0:
    value: 1
grad_clip_rms:
    value: 1
initial_L0:
    value: 1
learning_rate:
    value: 0.001
min_connections:
    value: 1
min_lr_ratio:
    value: 0
norm_type:
    value: rmsnorm
num_heads:
    value: 4
num_layers:
    value: 2
num_steps:
    value: 10000
operation:
    value: x+y
prime:
    value: 97
regularization_type:
    value: l0
training_fraction:
    value: 0.5
use_L0_lr_scaling:
    value: false
use_cosine_decay:
    value: true
warmup_ratio:
    value: 0.01
weight_decay:
    value: 0.1
